version: '3.5'

services:

  app-miangular:
    container_name: app-miangular
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
